#+TITLE: 《《堕落的村书记 石凤刚黑社会性质犯罪团伙覆灭》观后感》

** 石凤刚本来是辛庄村一名普通村民。在2013年通过威逼利诱的手段操纵选举，获得他梦寐以求的村委书记一职后，走上了欺压村民，疯狂敛财犯罪之路。其亲属在他的庇护下，为所欲为，肆无忌惮。他和儿子石阳在2013-2018年间，在北京市丰台区长辛店镇辛庄村范围内，先后纠集被告人于万、赵书连、于冠珍、王永胜、张亮等二十余名团伙成员，通过把持基层政权，形成人数较多、结构稳定、分工明确的黑社会性质组织。
该组织为形成强势地位、树立非法权威、逞强争霸，攫取非法利益，通过暴力、威胁等手段，有组织地实施寻衅滋事、故意伤害、敲诈勒索、强迫交易、故意毁坏财物、非法持有枪支等违法犯罪活动，为非作恶，欺压、残害群众；通过有组织地实施贪污、索要及收受贿赂、职务侵占、串通投标、非法占用农用地等犯罪活动，并在有关国家机关工作人员的纵容下，大肆毁林，垄断辛庄村土地资源，破坏辛庄村生态环境，非法聚敛巨额财富；通过渗透、把持基层政权、违规发展组织成员入党、违法为组织成员获取人大代表政治地位、聚众冲击国家机关、阻碍军人执行职务等违法犯罪活动，干扰国家机关、人民军队在当地的正常工作秩序，损害基层政权基础，危害国防利益；通过实施违法犯罪活动，并利用国家工作人员的纵容，在当地形成非法控制和重大影响，致使当地群众的合法权益被侵害后，不敢通过正常途径控告、举报，严重破坏了当地的政治、经济、社会生活秩序及生态环境。
** 从这个案件中我们可以总结出两点教训：
*** 石凤刚本来是辛庄村一名普通村民。在2013年通过威逼利诱的手段操纵选举，获得他梦寐以求的村委书记一职后，走上了欺压村民，疯狂敛财犯罪之路。其亲属在他的庇护下，为所欲为，肆无忌惮。他和儿子石阳在2013-2018年间，在北京市丰台区长辛店镇辛庄村范围内，先后纠集被告人于万、赵书连、于冠珍、王永胜、张亮等二十余名团伙成员，通过把持基层政权，形成人数较多、结构稳定、分工明确的黑社会性质组织。
*** 该组织为形成强势地位、树立非法权威、逞强争霸，攫取非法利益，通过暴力、威胁等手段，有组织地实施寻衅滋事、故意伤害、敲诈勒索、强迫交易、故意毁坏财物、非法持有枪支等违法犯罪活动，为非作恶，欺压、残害群众；通过有组织地实施贪污、索要及收受贿赂、职务侵占、串通投标、非法占用农用地等犯罪活动，并在有关国家机关工作人员的纵容下，大肆毁林，垄断辛庄村土地资源，破坏辛庄村生态环境，非法聚敛巨额财富；通过渗透、把持基层政权、违规发展组织成员入党、违法为组织成员获取人大代表政治地位、聚众冲击国家机关、阻碍军人执行职务等违法犯罪活动，干扰国家机关、人民军队在当地的正常工作秩序，损害基层政权基础，危害国防利益；通过实施违法犯罪活动，并利用国家工作人员的纵容，在当地形成非法控制和重大影响，致使当地群众的合法权益被侵害后，不敢通过正常途径控告、举报，严重破坏了当地的政治、经济、社会生活秩序及生态环境。
从这个案件中我们可以总结出两点教训：
